name: CI Pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:


jobs:

  tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Clone Code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Run Unit Tests
        run: make test -B
