name: Release Pipeline

on:
  workflow_dispatch:
  release:
    types: [ published ]

jobs:


  tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Clone Code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Run Unit Tests
        run: make test -B

  # ------------------------------------------------------------------------------------------------------------------------

  build:
    name: Build Binaries
    needs: [ tests ]
    runs-on: ubuntu-latest
    steps:
      - name: Clone Code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Mount Cache
        uses: actions/cache@v3
        with:
          key: cache-build-${{ github.run_id }}
          path: |
            build

      - name: Build Binaries
        run: make build -B

  # ------------------------------------------------------------------------------------------------------------------------

  deploy:
    name: Deployment
    runs-on: ubuntu-latest
    needs: [ build ]
    steps:

      - uses: actions/checkout@v3

      - name: Mount Cache
        uses: actions/cache@v3
        with:
          key: cache-build-${{ github.run_id }}
          path: |
            build

      - name: Deployment to Server
        uses: bayssmekanique/action-simple-file-upload@v1
        with:
          host: ${{ secrets.SSH_PROD_HOST }}
          user: ${{ secrets.SSH_PROD_USER }}
          password: ${{ secrets.SSH_PROD_PWD }}
          src: ./build/
          dest: ${{ secrets.PROD_DOWNLOAD_DIR }}/
